### ISSUE TITLE
Getting the output of executed script ?

### ISSUE THREAD

**Issue by mundusnine** [rxi/console#2]
How would one go about getting the output of the build script ? 

Right now, I have a file like this:

```
local core = require "core"
local command = require "core.command"
local keymap = require "core.keymap"
local console = require "plugins.console"
local cmd = ""
if PLATFORM == "Windows" then
  cmd = "./build.bat"
else
  cmd = "./build.sh"
end

command.add(nil, {
  ["project:build-project"] = function()
    core.log "Building..."
    console.run {
      cmd,
      file_pattern = "(.*):(%d+):(%d+): (.*)$",
      on_complete = function() core.log "Build complete" end,
    }
  end
})

keymap.add { ["ctrl+b"] = "project:build-project" }
```
Basically, the default in the example. But say I have errors in the code that is built by the build.bat(or sh) and I would want to see the errors in the lite console. How would one do that ?

**Comment by mundusnine** [comment]
Oh and how did you get the output of the love.exe in the console also ? Do you have an example repo ?

**Comment by rxi** [comment]
Anything printed to `stdout` or `stderr` will appear in the console though it may have a delay if `flush` isn't used, eg, for love:
```lua
print "hello world"
io.flush()
```

**Comment by mundusnine** [comment]
Ok so I pulled the latest version 1.05. I think the issue isn't what I initially thought. 

I found some issues on my end but I think I found others also. I will make other issues for these. But output works right now so I will close this.
