### ISSUE TITLE
Using pushd and popd in batch script yields weird behaviour

### ISSUE THREAD

**Issue by mundusnine** [rxi/console#3]
When having a batch script that uses the pushd and popd commands, the other commands in the script don't seem to be called(i.e. the file doesnt build given this file):

```
@echo off
if not exist build mkdir build
pushd build
rm app.exe
gcc ..\\src\\main.c -o app.exe
popd
```
the script works in normals cmd.exe

**Comment by rxi** [comment]
This works as expected for me in `1.05`. You may need to update to the latest release of `lite` and latest version of `console`:
![image](https://user-images.githubusercontent.com/3920290/82757379-032d0400-9dd8-11ea-82a1-1f8091f45fe5.png)

**Comment by mundusnine** [comment]
Ok; will update and report back.

**Comment by mundusnine** [comment]
Pushd and popd now work as expected
